### ISSUE TITLE
Backend failed to start up TypeError: Cannot read properties of undefined (reading 'fromConfig')

### ISSUE THREAD

**Issue by flrajjaladi** [AxisCommunications/backstage-plugins#44]
### Describe the bug
Unable to start the project post adding the Jira backend plugin getting the following error 
```
Backend failed to start up TypeError: Cannot read properties of undefined (reading 'fromConfig')
```

### To reproduce

1. Set up a new backstage project . 
2. Added the plugin by following the documentation including the steps adding the three lines required. 

-   Create a new file with the name `jiraDashboard.ts`.
-   Added the following lines into `src/index.ts`.

```ts
import jiraDashboard from './plugins/jiraDashboard';
 
// Add this line into main()
  const jiraDashboardEnv = useHotMemoize(module, () => createEnv('jira-dashboard'));
  
// Add this following line into the existing routes
  apiRouter.use('/jira-dashboard', await jiraDashboard(jiraDashboardEnv));

```

```ts
yarn dev
yarn run v1.22.21
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml, app-config.local.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/<username>/test_projects/developer-activity/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all
[0] webpack compiled successfully
[1] Loaded config from app-config.yaml, app-config.local.yaml
[1] 2024-01-04T13:43:13.564Z backstage info Found 3 new secrets in config that will be redacted
[1] ObservableConfigProxy {
[1]   parent: undefined,
[1]   parentKey: undefined,
[1]   config: ConfigReader {
[1]     data: { proxy: [Object] },
[1]     context: 'app-config.local.yaml',
[1]     fallback: ConfigReader {
[1]       data: [Object],
[1]       context: 'app-config.yaml',
[1]       fallback: undefined,
[1]       prefix: '',
[1]       filteredKeys: undefined,
[1]       notifiedFilteredKeys: Set(0) {}
[1]     },
[1]     prefix: '',
[1]     filteredKeys: undefined,
[1]     notifiedFilteredKeys: Set(0) {}
[1]   },
[1]   subscribers: [ [Function (anonymous)] ]
[1] }
[1] Backend failed to start up TypeError: Cannot read properties of undefined (reading 'fromConfig')
[1]     at makeCreateEnv (/Users/<username>/test_projects/developer-activity/packages/backend/src/index.ts:43:35)
[1]     at main (/Users<username>/test_projects/developer-activity/packages/backend/src/index.ts:86:21)
```

### Additional context
 - Tried both available version 0.1.0 and 0.2.0 still encountering same issue

**Comment by anicke** [comment]
Reopening...

**Comment by anicke** [comment]
Reopening

**Comment by fridajac** [comment]
I'm closing this issue since it has not had recent activity. @flrajjaladi Please let us know if you are still having this issue, and we will reopen it.
